### ISSUE TITLE
Create an "Awesome Anchor Positioning" repo

### ISSUE THREAD

**Issue by jamesnw** [oddbird/awesome-anchor-positioning#1]
- [x] @SondraE Review
- [x] @jgerigmeyer Review
- [x] Add PR Template
- [x] @jamesnw Make public
- [x] @SondraE Make public

**Comment by SondraE** [comment]
@jamesnw 
Awesome!
I found a couple small typos that I fixed in the README.

Would the README be a good place to say, 'sponsor us or hire us to finish building this'? 
We have the sponsor us part of that message already. Could we add the other half? 
Would we want to link people to Open Collective where they can see updates on the work we've done and how we've spent the money?

**Comment by jamesnw** [comment]
> Would the README be a good place to say, 'sponsor us or hire us to finish building this'?
> We have the sponsor us part of that message already. Could we add the other half?

@SondraE  I think that's a great idea. Do you have suggested wording? 

> Would we want to link people to Open Collective where they can see updates on the work we've done and how we've spent the money?

I'm not opposed to adding that. I copied this from the [polyfill](https://github.com/oddbird/css-anchor-positioning?tab=readme-ov-file#sponsor-oddbirds-oss-work) page- I think we thought "we're on Github, so link to Github"? We do have a link to the Open Collective in the sidebar.

**Comment by SondraE** [comment]
@jamesnw 

Maybe something like:

## Support OddBird's Anchor Positioning Work

At [OddBird](oddbird.dev), we love contributing to the languages & tools developers rely on. We're currently working on polyfills for new Popover & Anchor Positioning functionality, as well as CSS specifications for functions, mixins, and responsive typography. 

There are 2 ways to help us keep this work sustainable and centered on your needs as a developer!

1. [Sponsor us](https://github.com/sponsors/oddbird). We display sponsor logos and avatars on our [website](https://www.oddbird.net/polyfill/#open-source-sponsors) and offer [other fun perks](https://github.com/sponsors/oddbird).
2. [Hire us](https://www.oddbird.net/contact/) to develop the Anchor Positioning polyfill or another OSS language/tool you rely on. 

[Get OSS Work & Expense Updates](https://opencollective.com/oddbird-open-source)

@mirisuzanne What do you think of this suggested wording for the Awesome Anchor Positioning" repo? Would we want to change the "CSS specifications for functions, mixins, and responsive typography" section to be some W3C-specific task? This wording (with minor variations) could then go on other READMEs too.

**Comment by jamesnw** [comment]
> 2\. [Hire us](https://www.oddbird.net/contact/) to develop Anchor Positioning

I updated it slightly to specify "polyfill" here so people don't think they can hire us to build it in Firefox.

**Comment by jamesnw** [comment]
Potential promotional posts:

Anchor positioning is awesome, so we made Awesome Anchor Positioning to curate documentation, how-tos and awesome demos. What are we missing? Open a PR and let us know! [link]

Anchor positioning was the top feature in State of CSS 2024 that developers want to use but can't because of browser incompatibilities. We're curating resources on how to get started with learning (and using) anchor positioning today. [link]

**Comment by mirisuzanne** [comment]
@SondraE that text looks good to me!

**Comment by jgerigmeyer** [comment]
LGTM! 🚀
